### ISSUE TITLE
LEARN: Python Train + Test Codelab

### ISSUE THREAD

**Issue by grewe** [grewe/covid_id#11]
EVERY student (you can choose to do together in your project groups-MASK, FEVER, CROWD, SOCDIST) should do the following 
[http://borg.csueastbay.edu/~grewe/CS663/Mat/DeepLearning/Training/JupyterNotebookTensorflowExampleCatDog.html](http://borg.csueastbay.edu/~grewe/CS663/Mat/DeepLearning/Training/JupyterNotebookTensorflowExampleCatDog.html)

**Comment by One2Remember** [comment]
just finished this exercise - very neat!

**Comment by subhangi16** [comment]
done!

**Comment by immdivyagupta** [comment]
Done

**Comment by dikshantjn** [comment]
done
